import './globals.css'
import Nav from './components/Nav'
import { garamond, upright } from './fonts'



export const metadata = {
  title: 'Restaurant L\'Atelier',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      <html lang="en">
        <body className={`${garamond.variable} ${upright.variable}`}>
          <Nav />
          {children}
        </body>
      </html>
    </>
  )
}
